import { aimsStudentAccounts } from "../Models/aimsStudentInfoModel.js";

export const insertStudentsInfo = async () => {
  try {
    const existingSubject = await aimsStudentAccounts.findAll();

    if (existingSubject.length === 0) {
      const Subject = [
        {
          studentNumber: 20231001,
          first_name: "Jan",
          middle_name: "Ivan",
          last_name: "Montenegro",
          course: "BSIT",
          year: "2",
          role: "Student",
          section: "B",
          email: "20231001@gmail.com",
          phoneNumber: "09123456781",
          password: "Montenegro",
        },
        {
          studentNumber: 20231002,
          first_name: "Maria",
          middle_name: "L.",
          last_name: "Santos",
          course: "BSCS",
          year: "1",
          role: "Student",
          section: "A",
          email: "20231002@gmail.com",
          phoneNumber: "09123456782",
          password: "Santos",
        },
        {
          studentNumber: 20231003,
          first_name: "Carlos",
          middle_name: "D.",
          last_name: "Reyes",
          course: "BSIT",
          year: "3",
          role: "Student",
          section: "C",
          email: "20231003@gmail.com",
          phoneNumber: "09123456783",
          password: "Reyes",
        },
        {
          studentNumber: 20231004,
          first_name: "Andrea",
          middle_name: "F.",
          last_name: "Cruz",
          course: "BSCS",
          year: "2",
          role: "Student",
          section: "B",
          email: "20231004@gmail.com",
          phoneNumber: "09123456784",
          password: "Cruz",
        },
        {
          studentNumber: 20231005,
          first_name: "Luis",
          middle_name: "J.",
          last_name: "Garcia",
          course: "BSIT",
          year: "4",
          role: "Student",
          section: "D",
          email: "20231005@gmail.com",
          phoneNumber: "09123456785",
          password: "Garcia",
        },
        {
          studentNumber: 20231006,
          first_name: "Patricia",
          middle_name: "M.",
          last_name: "Rivera",
          course: "BSCS",
          year: "3",
          role: "Student",
          section: "A",
          email: "20231006@gmail.com",
          phoneNumber: "09123456786",
          password: "Rivera",
        },
        {
          studentNumber: 20231007,
          first_name: "Mark",
          middle_name: "E.",
          last_name: "Mendoza",
          course: "BSIT",
          year: "1",
          role: "Student",
          section: "B",
          email: "20231007@gmail.com",
          phoneNumber: "09123456787",
          password: "Mendoza",
        },
        {
          studentNumber: 20231008,
          first_name: "Samantha",
          middle_name: "T.",
          last_name: "Diaz",
          course: "BSCS",
          year: "4",
          role: "Student",
          section: "C",
          email: "20231008@gmail.com",
          phoneNumber: "09123456788",
          password: "Diaz",
        },
        {
          studentNumber: 20231009,
          first_name: "John",
          middle_name: "R.",
          last_name: "Torres",
          course: "BSIT",
          year: "2",
          role: "Student",
          section: "D",
          email: "20231009@gmail.com",
          phoneNumber: "09123456789",
          password: "Torres",
        },
        {
          studentNumber: 20231010,
          first_name: "Kimberly",
          middle_name: "P.",
          last_name: "Velasco",
          course: "BSCS",
          year: "3",
          role: "Student",
          section: "B",
          email: "20231010@gmail.com",
          phoneNumber: "09123456790",
          password: "Velasco",
        },
        {
          studentNumber: 20231011,
          first_name: "Michael",
          middle_name: "H.",
          last_name: "Cruz",
          course: "BSIT",
          year: "1",
          role: "Student",
          section: "A",
          email: "20231011@gmail.com",
          phoneNumber: "09123456791",
          password: "Cruz",
        },
        {
          studentNumber: 20231012,
          first_name: "Anna",
          middle_name: "L.",
          last_name: "Castillo",
          course: "BSCS",
          year: "2",
          role: "Student",
          section: "C",
          email: "20231012@gmail.com",
          phoneNumber: "09123456792",
          password: "Castillo",
        },
        {
          studentNumber: 20231013,
          first_name: "David",
          middle_name: "N.",
          last_name: "Bautista",
          course: "BSIT",
          year: "4",
          role: "Student",
          section: "B",
          email: "20231013@gmail.com",
          phoneNumber: "09123456793",
          password: "Bautista",
        },
        {
          studentNumber: 20231014,
          first_name: "Jessica",
          middle_name: "E.",
          last_name: "Lim",
          course: "BSCS",
          year: "3",
          role: "Student",
          section: "A",
          email: "20231014@gmail.com",
          phoneNumber: "09123456794",
          password: "Lim",
        },
        {
          studentNumber: 20231015,
          first_name: "Ryan",
          middle_name: "O.",
          last_name: "Villanueva",
          course: "BSIT",
          year: "2",
          role: "Student",
          section: "D",
          email: "20231015@gmail.com",
          phoneNumber: "09123456795",
          password: "Villanueva",
        },
        {
          studentNumber: 20231016,
          first_name: "Christine",
          middle_name: "S.",
          last_name: "Ramos",
          course: "BSCS",
          year: "1",
          role: "Student",
          section: "B",
          email: "20231016@gmail.com",
          phoneNumber: "09123456796",
          password: "Ramos",
        },
        {
          studentNumber: 20231017,
          first_name: "Joseph",
          middle_name: "T.",
          last_name: "Gomez",
          course: "BSIT",
          year: "3",
          role: "Student",
          section: "C",
          email: "20231017@gmail.com",
          phoneNumber: "09123456797",
          password: "Gomez",
        },
        {
          studentNumber: 20231018,
          first_name: "Sophia",
          middle_name: "D.",
          last_name: "Hernandez",
          course: "BSCS",
          year: "4",
          role: "Student",
          section: "D",
          email: "20231018@gmail.com",
          phoneNumber: "09123456798",
          password: "Hernandez",
        },
        {
          studentNumber: 20231019,
          first_name: "Nathan",
          middle_name: "W.",
          last_name: "Fernandez",
          course: "BSIT",
          year: "1",
          role: "Student",
          section: "A",
          email: "20231019@gmail.com",
          phoneNumber: "09123456799",
          password: "Fernandez",
        },
        {
          studentNumber: 20231020,
          first_name: "Isabella",
          middle_name: "C.",
          last_name: "Chua",
          course: "BSCS",
          year: "2",
          role: "Student",
          section: "B",
          email: "20231020@gmail.com",
          phoneNumber: "09123456800",
          password: "Chua",
        },
      ];
      await aimsStudentAccounts.bulkCreate(Subject);
      console.log("Students Information Inserted successfully");
    } else {
      console.log("Students Information already exist, skipping insertion.");
    }
  } catch (error) {
    console.error("Error inserting Students Information:", error);
  }
};
